version: "3"

services:
  autossh-transmission:
    image: jnovack/autossh:latest-arm32v7
    container_name: autossh-transmission
    restart: unless-stopped
    environment:
      - SSH_HOSTUSER=anbangtest
      - SSH_HOSTNAME=serveo.net
      - SSH_TUNNEL_REMOTE=80
      - SSH_TUNNEL_HOST=localhost
      - SSH_TUNNEL_LOCAL=9091
      - SSH_KNOWN_HOSTS=/home/pi/.ssh/known_hosts
